### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by sompylasar** [diegodoumecq/joymap#6]
Cannot use `joymap` from a CodeSandbox React app, which seems to also import `babel-polyfill`.

https://codesandbox.io/s/3xlknpxpnq

Similar errors:
- https://github.com/feathersjs/feathers/issues/185
- https://github.com/lebab/lebab/issues/249

Recommended solution:
- Do not import `babel-polyfill` in library code: https://babeljs.io/docs/en/babel-polyfill/#details 

------

<img width="1440" alt="screen shot 2018-07-08 at 5 07 43 pm" src="https://user-images.githubusercontent.com/498274/42425380-7b3b207c-82d1-11e8-88d2-a28ba21e4b76.png">

```
Error: only one instance of babel-polyfill is allowed
    at evaluate (https://3xlknpxpnq.codesandbox.io/node_modules/babel-polyfill/lib/index.js:10:9)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at d (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277743)
    at evaluate (https://3xlknpxpnq.codesandbox.io/node_modules/joymap/bin/index.js:8:1)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at d (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277743)
    at evaluate (https://3xlknpxpnq.codesandbox.io/src/index.js:11:15)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249167)
    at https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:67799
    at g (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156219)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156007)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156398)
    at n (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:169318)
    at https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:169414
```

Code:
```js
import React from "react";
import ReactDOM from "react-dom";

import { createJoyMap, createQueryModule } from "joymap";

const rootElement = document.getElementById("root");
ReactDOM.render(<div />, rootElement);
```

**Comment by diegodoumecq** [comment]
Thanks for bringing this up. `babel-polyfill` is clearly not made to be used by libraries. Removed on the recently published v1.0.2.
